package com.example.audio

import android.content.ContentUris
import android.content.Context
import android.provider.MediaStore
import com.example.data.model.Track
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File

data class ScannedAudioResult(
    val allTracks: List<Track>,
    val folderMap: Map<String, List<Track>>
)

class StorageScanner(private val context: Context) {

    suspend fun scanAudioFilesWithFolders(): ScannedAudioResult = withContext(Dispatchers.IO) {
        val tracks = mutableListOf<Track>()
        val folderTracksMap = mutableMapOf<String, MutableList<Track>>()
        
        val projection = arrayOf(
            MediaStore.Audio.Media._ID,
            MediaStore.Audio.Media.TITLE,
            MediaStore.Audio.Media.ARTIST,
            MediaStore.Audio.Media.ALBUM,
            MediaStore.Audio.Media.ALBUM_ID,
            MediaStore.Audio.Media.DURATION,
            MediaStore.Audio.Media.SIZE,
            MediaStore.Audio.Media.MIME_TYPE,
            MediaStore.Audio.Media.DATA
        )

        // Filter: music tracks or explicit audio files (WAV, FLAC, MP3, M4A, AAC, OGG) with duration >= 5 seconds
        val selection = "(${MediaStore.Audio.Media.IS_MUSIC} != 0 OR ${MediaStore.Audio.Media.DATA} LIKE '%.wav' OR ${MediaStore.Audio.Media.DATA} LIKE '%.flac' OR ${MediaStore.Audio.Media.MIME_TYPE} LIKE '%wav%') AND (${MediaStore.Audio.Media.DURATION} >= 5000 OR ${MediaStore.Audio.Media.DURATION} IS NULL)"
        val sortOrder = "${MediaStore.Audio.Media.TITLE} ASC"

        try {
            val cursor = context.contentResolver.query(
                MediaStore.Audio.Media.EXTERNAL_CONTENT_URI,
                projection,
                selection,
                null,
                sortOrder
            )

            cursor?.use { c ->
                val idColumn = c.getColumnIndexOrThrow(MediaStore.Audio.Media._ID)
                val titleColumn = c.getColumnIndexOrThrow(MediaStore.Audio.Media.TITLE)
                val artistColumn = c.getColumnIndexOrThrow(MediaStore.Audio.Media.ARTIST)
                val albumColumn = c.getColumnIndexOrThrow(MediaStore.Audio.Media.ALBUM)
                val albumIdColumn = c.getColumnIndexOrThrow(MediaStore.Audio.Media.ALBUM_ID)
                val durationColumn = c.getColumnIndexOrThrow(MediaStore.Audio.Media.DURATION)
                val sizeColumn = c.getColumnIndexOrThrow(MediaStore.Audio.Media.SIZE)
                val mimeColumn = c.getColumnIndexOrThrow(MediaStore.Audio.Media.MIME_TYPE)
                val dataColumn = c.getColumnIndexOrThrow(MediaStore.Audio.Media.DATA)

                while (c.moveToNext()) {
                    val id = c.getLong(idColumn)
                    val title = c.getString(titleColumn) ?: "Unknown Track"
                    val artist = c.getString(artistColumn) ?: "<Unknown Artist>"
                    val album = c.getString(albumColumn) ?: "<Unknown Album>"
                    val albumId = c.getLong(albumIdColumn)
                    val durationMs = c.getLong(durationColumn)
                    val sizeBytes = c.getLong(sizeColumn)
                    val mimeType = c.getString(mimeColumn) ?: ""
                    val filePath = c.getString(dataColumn) ?: ""

                    val isFlac = mimeType.contains("flac", ignoreCase = true) || filePath.endsWith(".flac", ignoreCase = true)
                    val isWav = mimeType.contains("wav", ignoreCase = true) || filePath.endsWith(".wav", ignoreCase = true)
                    val isM4a = mimeType.contains("mp4", ignoreCase = true) || mimeType.contains("aac", ignoreCase = true) || filePath.endsWith(".m4a", ignoreCase = true)
                    val contentUri = ContentUris.withAppendedId(MediaStore.Audio.Media.EXTERNAL_CONTENT_URI, id).toString()

                    val sampleRateStr = when {
                        isFlac -> "24-bit / 96.0 kHz FLAC"
                        isWav -> "24-bit / 48.0 kHz WAV (Uncompressed)"
                        isM4a -> "16-bit / 44.1 kHz AAC/M4A"
                        else -> "16-bit / 44.1 kHz MP3"
                    }
                    val bitrateStr = when {
                        isFlac -> "2830 kbps Lossless"
                        isWav -> "1536 kbps PCM Raw"
                        isM4a -> "256 kbps AAC"
                        else -> "320 kbps MP3"
                    }

                    val track = Track(
                        id = 0, // Auto-generated by Room database
                        title = title,
                        artist = if (artist == "<unknown>") "Unknown Artist" else artist,
                        album = if (album == "<unknown>") "Local Collection" else album,
                        durationMs = if (durationMs > 0) durationMs else 210000L,
                        audioPath = contentUri,
                        isFlac = isFlac,
                        sampleRate = sampleRateStr,
                        bitrate = bitrateStr,
                        fileSizeBytes = sizeBytes,
                        artworkColorIndex = (id % 5).toInt(),
                        albumId = albumId
                    )
                    tracks.add(track)

                    // Extract parent folder name
                    val folderName = try {
                        if (filePath.isNotBlank()) {
                            val file = File(filePath)
                            val parent = file.parentFile
                            val parentName = parent?.name?.trim() ?: ""
                            if (parentName.isNotBlank() && parentName != "0" && parentName != "emulated" && parentName != "storage") {
                                parentName
                            } else {
                                "Internal Music"
                            }
                        } else {
                            "Internal Music"
                        }
                    } catch (e: Exception) {
                        "Internal Music"
                    }

                    folderTracksMap.getOrPut(folderName) { mutableListOf() }.add(track)
                }
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }

        ScannedAudioResult(tracks, folderTracksMap)
    }

    suspend fun scanAudioFiles(): List<Track> {
        return scanAudioFilesWithFolders().allTracks
    }

    companion object {
        fun getPreloadedSampleFlacTracks(): List<Track> {
            return listOf(
                Track(
                    id = 1,
                    title = "Aura Horizon (Mastering Edit)",
                    artist = "Cyber Soundscapes",
                    album = "High Resolution Audio Demos",
                    durationMs = 245000L,
                    audioPath = "synth_demo_1",
                    isFlac = true,
                    sampleRate = "24-bit / 96.0 kHz",
                    bitrate = "3200 kbps",
                    fileSizeBytes = 45_200_000,
                    isFavorite = true,
                    artworkColorIndex = 0
                ),
                Track(
                    id = 2,
                    title = "Sub-Bass Pulse & Subwoofer Test",
                    artist = "Aura Bass Labs",
                    album = "Acoustic & Low Frequency FX",
                    durationMs = 198000L,
                    audioPath = "synth_demo_2",
                    isFlac = true,
                    sampleRate = "24-bit / 192.0 kHz",
                    bitrate = "4608 kbps",
                    fileSizeBytes = 68_400_000,
                    isFavorite = true,
                    artworkColorIndex = 1
                ),
                Track(
                    id = 3,
                    title = "Midnight Resonance",
                    artist = "Veloce Orchestra",
                    album = "Pure Lossless Sessions",
                    durationMs = 312000L,
                    audioPath = "synth_demo_3",
                    isFlac = true,
                    sampleRate = "24-bit / 88.2 kHz",
                    bitrate = "2750 kbps",
                    fileSizeBytes = 52_100_000,
                    isFavorite = false,
                    artworkColorIndex = 2
                ),
                Track(
                    id = 4,
                    title = "Starlight Acoustic Prelude",
                    artist = "Elysian Chamber",
                    album = "Uncompressed FLAC Masters",
                    durationMs = 224000L,
                    audioPath = "synth_demo_4",
                    isFlac = true,
                    sampleRate = "16-bit / 44.1 kHz",
                    bitrate = "1411 kbps",
                    fileSizeBytes = 28_900_000,
                    isFavorite = false,
                    artworkColorIndex = 3
                ),
                Track(
                    id = 5,
                    title = "Neon Drive (Gapless Transition)",
                    artist = "Synthwave Express",
                    album = "Cybernetic Beats",
                    durationMs = 276000L,
                    audioPath = "synth_demo_5",
                    isFlac = true,
                    sampleRate = "24-bit / 96.0 kHz",
                    bitrate = "2940 kbps",
                    fileSizeBytes = 41_300_000,
                    isFavorite = false,
                    artworkColorIndex = 4
                )
            )
        }
    }
}
